<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TestVagrants-MacBook-Pro.local" failures="15" tests="15" name="Test" time="0.171" errors="0" timestamp="2023-08-17T08:23:53 IST">
  <testcase classname="exceptionTests.StringOperation" name="shouldCompareCaseSensitiveString" time="0.021">
    <failure type="java.lang.AssertionError" message="Comparison of Strings failed expected [0] but found [-32]">
      <![CDATA[java.lang.AssertionError: Comparison of Strings failed expected [0] but found [-32]
at exceptionTests.StringOperation.shouldCompareCaseSensitiveString(StringOperation.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- shouldCompareCaseSensitiveString -->
  <testcase classname="exceptionTests.StringOperation" name="shouldCompareCaseSensitiveString2" time="0.002">
    <failure type="java.lang.AssertionError" message="Comparison of Strings failed expected [0] but found [-32]">
      <![CDATA[java.lang.AssertionError: Comparison of Strings failed expected [0] but found [-32]
at exceptionTests.StringOperation.shouldCompareCaseSensitiveString2(StringOperation.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- shouldCompareCaseSensitiveString2 -->
  <testcase classname="exceptionTests.StringOperation" name="shouldCompareCaseSensitiveString3" time="0.002">
    <failure type="java.lang.AssertionError" message="Comparison of Strings failed expected [0] but found [-32]">
      <![CDATA[java.lang.AssertionError: Comparison of Strings failed expected [0] but found [-32]
at exceptionTests.StringOperation.shouldCompareCaseSensitiveString3(StringOperation.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- shouldCompareCaseSensitiveString3 -->
  <testcase classname="exceptionTests.StringOperation" name="shouldCompareCaseSensitiveString4" time="0.002">
    <failure type="java.lang.AssertionError" message="Comparison of Strings failed expected [0] but found [-32]">
      <![CDATA[java.lang.AssertionError: Comparison of Strings failed expected [0] but found [-32]
at exceptionTests.StringOperation.shouldCompareCaseSensitiveString4(StringOperation.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- shouldCompareCaseSensitiveString4 -->
  <testcase classname="exceptionTests.StringOperation" name="testStringConcatenation" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.pass(String)&amp;quot; because the return value of &amp;quot;reports.ExtendManager.getExtentTest()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because the return value of "reports.ExtendManager.getExtentTest()" is null
at reports.FrameworkeLogger.lambda$0(FrameworkeLogger.java:13)
at reports.FrameworkeLogger.log(FrameworkeLogger.java:35)
at listener.Listener.onTestSuccess(Listener.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testStringConcatenation -->
  <testcase classname="exceptionTests.StringOperation" name="testStringContains" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.pass(String)&amp;quot; because the return value of &amp;quot;reports.ExtendManager.getExtentTest()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because the return value of "reports.ExtendManager.getExtentTest()" is null
at reports.FrameworkeLogger.lambda$0(FrameworkeLogger.java:13)
at reports.FrameworkeLogger.log(FrameworkeLogger.java:35)
at listener.Listener.onTestSuccess(Listener.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testStringContains -->
  <testcase classname="exceptionTests.StringOperation" name="testStringLength" time="0.001">
    <failure type="java.lang.AssertionError" message="Incorrect string length expected [13] but found [14]">
      <![CDATA[java.lang.AssertionError: Incorrect string length expected [13] but found [14]
at exceptionTests.StringOperation.testStringLength(StringOperation.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testStringLength -->
  <testcase classname="exceptionTests.StringOperation" name="testStringLowerCase" time="0.001">
    <failure type="java.lang.AssertionError" message="Lowercase conversion failed expected [testnG] but found [testng]">
      <![CDATA[java.lang.AssertionError: Lowercase conversion failed expected [testnG] but found [testng]
at exceptionTests.StringOperation.testStringLowerCase(StringOperation.java:119)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testStringLowerCase -->
  <testcase classname="exceptionTests.StringOperation" name="testStringSubstring" time="0.002">
    <failure type="java.lang.AssertionError" message="Substring mismatch expected [awesome] but found [ awesom]">
      <![CDATA[java.lang.AssertionError: Substring mismatch expected [awesome] but found [ awesom]
at exceptionTests.StringOperation.testStringSubstring(StringOperation.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testStringSubstring -->
  <testcase classname="exceptionTests.StringOperation" name="testStringUpperCase" time="0.005">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.pass(String)&amp;quot; because the return value of &amp;quot;reports.ExtendManager.getExtentTest()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because the return value of "reports.ExtendManager.getExtentTest()" is null
at reports.FrameworkeLogger.lambda$0(FrameworkeLogger.java:13)
at reports.FrameworkeLogger.log(FrameworkeLogger.java:35)
at listener.Listener.onTestSuccess(Listener.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testStringUpperCase -->
  <testcase classname="exceptionTests.ExceptionTest" name="testArithmeticException" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at exceptionTests.ExceptionTest.testArithmeticException(ExceptionTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testArithmeticException -->
  <testcase classname="exceptionTests.ExceptionTest" name="testArithmeticException2" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at exceptionTests.ExceptionTest.testArithmeticException2(ExceptionTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testArithmeticException2 -->
  <testcase classname="exceptionTests.ExceptionTest" name="testIndexOutOfBoundsException" time="0.001">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 10 out of bounds for length 5">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 5
at exceptionTests.ExceptionTest.testIndexOutOfBoundsException(ExceptionTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOutOfBoundsException -->
  <testcase classname="exceptionTests.ExceptionTest" name="testMultipleExceptions" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.length()&amp;quot; because &amp;quot;str&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at exceptionTests.ExceptionTest.testMultipleExceptions(ExceptionTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testMultipleExceptions -->
  <testcase classname="exceptionTests.ExceptionTest" name="testNullPointerException" time="0.017">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.length()&amp;quot; because &amp;quot;str&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at exceptionTests.ExceptionTest.testNullPointerException(ExceptionTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testNullPointerException -->
</testsuite> <!-- Test -->
