<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TestVagrants-MacBook-Pro.local" failures="9" tests="12" name="Test" time="0.133" errors="0" timestamp="2023-08-17T14:46:23 IST">
  <testcase classname="exceptionTests.StringOperation" name="compareCaseSensitiveString" time="0.02">
    <failure type="java.lang.AssertionError" message="Comparison of Strings failed expected [0] but found [-32]">
      <![CDATA[java.lang.AssertionError: Comparison of Strings failed expected [0] but found [-32]
at exceptionTests.StringOperation.compareCaseSensitiveString(StringOperation.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- compareCaseSensitiveString -->
  <testcase classname="exceptionTests.StringOperation" name="stringConcatenation" time="0.001"/>
  <testcase classname="exceptionTests.StringOperation" name="stringContains" time="0.002"/>
  <testcase classname="exceptionTests.StringOperation" name="stringLength" time="0.001">
    <failure type="java.lang.AssertionError" message="Incorrect string length expected [13] but found [14]">
      <![CDATA[java.lang.AssertionError: Incorrect string length expected [13] but found [14]
at exceptionTests.StringOperation.stringLength(StringOperation.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- stringLength -->
  <testcase classname="exceptionTests.StringOperation" name="stringToLowerCase" time="0.001">
    <failure type="java.lang.AssertionError" message="Lowercase conversion failed expected [testnG] but found [testng]">
      <![CDATA[java.lang.AssertionError: Lowercase conversion failed expected [testnG] but found [testng]
at exceptionTests.StringOperation.stringToLowerCase(StringOperation.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- stringToLowerCase -->
  <testcase classname="exceptionTests.StringOperation" name="stringToSubstring" time="0.001">
    <failure type="java.lang.AssertionError" message="Substring mismatch expected [awesome] but found [ awesom]">
      <![CDATA[java.lang.AssertionError: Substring mismatch expected [awesome] but found [ awesom]
at exceptionTests.StringOperation.stringToSubstring(StringOperation.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- stringToSubstring -->
  <testcase classname="exceptionTests.StringOperation" name="stringToUpperCase" time="0.006"/>
  <testcase classname="exceptionTests.ExceptionTest" name="testArithmeticException" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at exceptionTests.ExceptionTest.testArithmeticException(ExceptionTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testArithmeticException -->
  <testcase classname="exceptionTests.ExceptionTest" name="testArithmeticException2" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at exceptionTests.ExceptionTest.testArithmeticException2(ExceptionTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testArithmeticException2 -->
  <testcase classname="exceptionTests.ExceptionTest" name="testIndexOutOfBoundsException" time="0.003">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 10 out of bounds for length 5">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 5
at exceptionTests.ExceptionTest.testIndexOutOfBoundsException(ExceptionTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOutOfBoundsException -->
  <testcase classname="exceptionTests.ExceptionTest" name="testMultipleExceptions" time="0.003">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.length()&amp;quot; because &amp;quot;str&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at exceptionTests.ExceptionTest.testMultipleExceptions(ExceptionTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testMultipleExceptions -->
  <testcase classname="exceptionTests.ExceptionTest" name="testNullPointerException" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.length()&amp;quot; because &amp;quot;str&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
at exceptionTests.ExceptionTest.testNullPointerException(ExceptionTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testNullPointerException -->
</testsuite> <!-- Test -->
